### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by CryptoCopter** [Zayus13/OrderBot#20]
when running `!ob --payout` when there is no one with a negative balance:

```
DEBUG|2022-06-14 11:29:03,938: Namespace(func=<function parse_input.<locals>.payout at 0x7fd019b60940>, name=['markus', 'sommer'])
Traceback (most recent call last):
  File "./orderbot.py", line 154, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./orderbot.py", line 150, in main
    await bot.listen()
  File "./orderbot.py", line 93, in listen
    sync_response = await self.client.sync(60000)
  File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 1046, in sync
    response = await self._send(
  File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 792, in _send
    await self.receive_response(resp)
  File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 704, in receive_response
    await self._handle_sync(response)
  File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 671, in _handle_sync
    await self._handle_joined_rooms(response)
  File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 598, in _handle_joined_rooms
    await asyncio.coroutine(cb.func)(room, event)
  File "./orderbot.py", line 129, in message_cb
    order, response = order_parser.parse_input(inp, self.session, self.order, event.sender, self.members)
  File "/order_parser.py", line 396, in parse_input
    result = args.func(vars(args))
  File "/order_parser.py", line 241, in payout
    update(Participant).where(Participant.pid == all_user_subset[0].pid)
IndexError: list index out of range
ERROR|2022-06-14 11:29:03,974: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd01a5abc70>
ERROR|2022-06-14 11:29:03,974: Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd01a5c6dc0>, 615519.32683526)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd01a5abcd0>
```

**Comment by Zayus13** [comment]
done
