### ISSUE TITLE
Crash at order cancel

### ISSUE THREAD

**Issue by CryptoCopter** [Zayus13/OrderBot#22]
```
INFO|2022-06-23 18:02:09,936: Body:!ob start test, Msg:Started new collective order with Name: test
usage: OrderBot options: add [-h] [--name NAME]
                             [order name [order name ...]] price

positional arguments:
  order name            name of order
  price                 price of order

optional arguments:
  -h, --help            show this help message and exit
  --name NAME, -n NAME  orderer, if different from messenger, in quotes
INFO|2022-06-23 18:02:32,878: Body:!ob add --help, Msg:usage: OrderBot options: add [-h] [--name NAME]
                             [order name [order name ...]] price

positional arguments:
  order name            name of order
  price                 price of order

optional arguments:
  -h, --help            show this help message and exit
  --name NAME, -n NAME  orderer, if different from messenger, in quotes

DEBUG|2022-06-23 18:02:48,309: Namespace(func=<function parse_input.<locals>.add at 0x7f763a100550>, name=None, price=-99999.0, **{'order name': ['foobar']})
INFO|2022-06-23 18:02:48,328: Body:!ob add foobar -99999, Msg:Order added for markus sommer, order: foobar, price: -99999.00
DEBUG|2022-06-23 18:03:08,876: Namespace(func=<function parse_input.<locals>.cancel at 0x7f763a103ca0>)
INFO|2022-06-23 18:03:08,876: Body:!ob cancel , Msg:Cancelled current collective order
Traceback (most recent call last):
  File "./orderbot.py", line 154, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./orderbot.py", line 150, in main
    await bot.listen()
  File "./orderbot.py", line 95, in listen
    next_batch_token.write(sync_response.next_batch)
AttributeError: 'SyncError' object has no attribute 'next_batch'
ERROR|2022-07-04 15:38:25,117: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f763ab23ca0>
ERROR|2022-07-04 15:38:25,117: Unclosed connector
```

**Comment by Zayus13** [comment]
Hmmm, SyncError spricht da für ein Verbindungsproblem, muss ich ggf vorher abfangen
