### ISSUE TITLE
Trying to pay for an order crashes the daemon

### ISSUE THREAD

**Issue by CryptoCopter** [Zayus13/OrderBot#38]
```
DEBUG|2022-11-03 13:22:02,677: Namespace(amount=53.0, func=<function parse_input.<locals>.pay at 0x7f3f10e610d0>, name=None, order=True)
Traceback (most recent call last):
  File "./orderbot.py", line 163, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./orderbot.py", line 159, in main
    await bot.listen()
  File "./orderbot.py", line 94, in listen
    sync_response = await self.client.sync(6000)
  File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 1046, in sync
    response = await self._send(
  File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 792, in _send
    await self.receive_response(resp)
  File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 704, in receive_response
    await self._handle_sync(response)
  File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 671, in _handle_sync
    await self._handle_joined_rooms(response)
  File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 598, in _handle_joined_rooms
    await asyncio.coroutine(cb.func)(room, event)
  File "./orderbot.py", line 138, in message_cb
    order, response = order_parser.parse_input(inp, self.session, self.order, event.sender, self.members)
  File "/order_parser.py", line 498, in parse_input
    result = args.func(vars(args))
  File "/order_parser.py", line 218, in pay
    save_order_in_db(order, session)
  File "/order_parser.py", line 68, in save_order_in_db
    tip_shares = split_tip(order.tip, len(order.order))
  File "/order_parser.py", line 51, in split_tip
    for i in range(too_much):
TypeError: 'float' object cannot be interpreted as an integer
ERROR|2022-11-03 13:22:02,718: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3f11902df0>
ERROR|2022-11-03 13:22:02,718: Unclosed connector
```

**Comment by CryptoCopter** [comment]
```
Mam
markus:	 Pizza Toscana : 6.00
artur:	 Pizzabrötchen mit Spezialsauce : 3.00
jonas:	 Pizza Ombrello : 6.00
michael:	 Pizza India : 6.00, Pizza Bella-Bello : 6.00
christian:  Pizza Ombrello : 6.00
patrick:	 Pizza Quattro Formaggi : 6.00
roland:	 Salat Greek : 6.00, Salat City : 6.00
Tip:	 0.00
Total:	 51.00
Sum:	 51.00
Paid by: None
```

**Comment by Zayus13** [comment]
`an unnamed order
"markus":	 unknown Meal : 6.00
"artur":	 unknown Meal : 3.00
"jonas":	 unknown Meal : 6.00
"michael":	 unknown Meal : 6.00, unknown Meal : 6.00
"chris":	 unknown Meal : 6.00
"pat":	 unknown Meal : 6.00
"roland":	 unknown Meal : 6.00, unknown Meal : 6.00
Tip:	 2.00
Total:	 51.00
Sum:	 53.00
Paid by: "artur"
!ob users balance
DEBUG|2022-11-07 23:05:56,993: Namespace(users=True, func=<function parse_input.<locals>.balance at 0x00000159726F93F0>)
INFO|2022-11-07 23:05:56,998: Current balances: 
"artur" (None):	 49.71
"sven" (None):	 0.00
"roladn" (None):	 0.00
"jonas" (None):	 -6.28
"pat" (None):	 -6.28
"markus" (None):	 -6.29
"chris" (None):	 -6.29
"roland" (None):	 -12.28
"michael" (None):	 -12.29`
reprocudes situation, works fine now
